name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover /p:Threshold=80 --no-build --verbosity normal
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: coverage
        color: brightgreen
        path: tests/PowerPipe.UnitTests/TestResults/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: 87b833b49852f7f088e1d4d913600a91
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
